### ISSUE TITLE
The code might need a bit of a update

### ISSUE THREAD

**Issue by thinkpad4** [LeagueRaINi/Aida64-Keys#2]
@LeagueRaINi The keys generated aren't working anymore.  The ones in the preview aren't working on the latest beta of Aida.  Also how to I get this to run or make it a exe?  Thank you very much

**Comment by LeagueRaINi** [comment]
Tool works perfectly fine.
![raw](https://user-images.githubusercontent.com/19365835/188617438-40261961-ea4a-4c8e-af9b-1a0253fe3e7f.png)
