### ISSUE TITLE
Small bug?

### ISSUE THREAD

**Issue by justakingalook** [LeagueRaINi/Aida64-Keys#3]
Hi, i noticed that occasionally, your code generate non valid keys (testing it, i got around 8 non valid keys for 1000 generated keys)

Those keys are not "totally" faulty, as they only fail in the last character (once you "brute force them" and put the correct character, key is totally fine).

I saved those non valid keys in case you wanna take a look at them (just for curiosity or perfectionism, as your code is working flawless)

Cheers!

![2022_09_06_13_39_47_AIDA64_Extreme](https://user-images.githubusercontent.com/108824189/188627993-1732b0ba-81cf-44d3-bfaf-2642f7ddd83e.png)

**Comment by LeagueRaINi** [comment]
interesting, almost sure its date related and that i broke it while cleaning up, mind sending me the keys that fail?

**Comment by justakingalook** [comment]
Sure, here they are:

4QL8RKYQD6B1DTSXDG4YG4NUN
UUYZ1RFID69YD947DM9Y9MHEN
4U5BUCYAD69ZDTE1DAMYAMQ8W
RF3U19FPD6CCDT84DP8Y9XKLG
R16IDLFID6CWDT8UDP2Y9HKXI
YYGN3ED5D66IDTPADSKYSKTGB
17ABRI1PD6QADTS7DA5YABN63
1HX6F2YGD6BQDTG2D57Y5G5FJ

**Comment by LeagueRaINi** [comment]
looks like something aint right with the way i'm doing the checksum, might look into that when i got time the next days

some more i collected
```
Invalid key found! U5QI1T3ID69JD946D8FYNQHJ6
          - valid: U5QI1T3ID69JD946D8FYNQHJI
Invalid key found! YZIKFE4KD65YDT7BD59Y59BEA
          - valid: YZIKFE4KD65YDT7BD59Y59BEG
Invalid key found! D1TBF749D6IBDT2SDGTYGT95M
          - valid: D1TBF749D6IBDT2SDGTYGT958
Invalid key found! UJIX17FUD6LVDT8PD8YYNKI3T
          - valid: UJIX17FUD6LVDE8PD8YYNKI3E
Invalid key found! DH9BUB19D6A5D9D4DGSYGSLM2
          - valid: DH9BUB19D6A5D9D4DGSYGSLMP
Invalid key found! 3BISDE3AD6JJD9Y6DPFYTNCJG
          - valid: 3BISDE3AD6JJD9Y6DPFYTNCJS
Invalid key found! UC811PFQD6F9DT5KDMPYNWA7Z
          - valid: UC811PFQD6F9DT5KDMPYNWA77
Invalid key found! F7W6YHRQD6CJDTMQD2AYTFJJT
          - valid: F7W6YHRQD6CJD9MQD2AY9FJJ9
Invalid key found! 1ZTG3N18D6MAD93MDA9YA93T4
          - valid: 1ZTG3N18D6MAD93MDA9YA93TU
Invalid key found! 4W5QFJDFD6MTD93GDA7YAG3RV
          - valid: 4W5QFJDFD6MTD93GDA7YAG3RZ
Invalid key found! YURAUEYED6H1DT9WDSNYSQPUJ
          - valid: YURAUEYED6H1DT9WDSNYSQPUT
Invalid key found! DZJZ361DD6WWDTJ9DSLYSUPQA
          - valid: DZJZ361DD6WWDTJ9DSLYSUPQG
Invalid key found! 422EYH3DD69UD9U4DMWY9SWCG
          - valid: 422EYH3DD69UD9U4DMWY9SWCS
Invalid key found! RUM2DQ3XD612DTNTDP8Y9XGVH
          - valid: RUM2DQ3XD612DTNTDP8Y9XGVW
Invalid key found! 1RFZ3H45D68QD9F5D5VY5VRWG
          - valid: 1RFZ3H45D68QD9F5D5VY5VRWS
Invalid key found! RLCN16FLD61JDTNXDM4Y9TG57
          - valid: RLCN16FLD61JDTNXDM4Y9TG5E
Invalid key found! D6C8FZ1FD6ZQD9R5DGVYG5FWV
          - valid: D6C8FZ1FD6ZQD9R5DG1YG5FW1
Invalid key found! 17PDR319D6N3DTEKDAAYA6QVJ
          - valid: 17PDR319D6N3DTEKDAAYA6QVT
Invalid key found! FLCKYFFSD6U2DTATD88Y545VH
          - valid: FLCKYFFSD6U2DTATD88Y545VW
```

**Comment by thinkpad4** [comment]
A side question, in your preview you are using powershell to run it, how do I get the program to run in Powershell?  Thank you very much

**Comment by justakingalook** [comment]
I downloaded last AIDA64 Beta version and couldn´t activate it, seems none of the keys are working, could u take a look?

Thanks in advance and regards.

**Comment by JyqJyx** [comment]
Hello, I am a computer novice. Thank you for your published work. You have published the source code, but I am not sure how to use it. Do you have any relevant tutorials that can teach me how to use these files? Because I can only double-click on some executable programs or batch files with the mouse, thank you!!!
