### ISSUE TITLE
Not really an issue with code/but idk how to use it

### ISSUE THREAD

**Issue by iVolgin69** [LeagueRaINi/Aida64-Keys#4]
Title

how do i run it?

ik this is dumb

**Comment by bygalacos** [comment]
Yesterday, i tried to build on ubuntu but it failed. It'll be good to have a builded version at the downloads section. Thanks for your effort.

**Comment by iVolgin69** [comment]
How can i build it on win10?

**Comment by ExtremeXBB** [comment]
#6

**Comment by ExtremeXBB** [comment]
#6 I wrote the documentation for building in Debian/Ubuntu
