### ISSUE TITLE
Back to Future

### ISSUE THREAD

**Issue by bygalacos** [LeagueRaINi/Aida64-Keys#5]
Im not sure if this is a bug or feature but you can activate keys from future :)

Thanks for this great tool btw, waiting stable releases for both console and gui version.

![image](https://user-images.githubusercontent.com/57764369/201441141-12a681e3-9abf-45de-93b9-242962d14c04.png)
![image](https://user-images.githubusercontent.com/57764369/201441293-566e4d71-f706-46c0-9506-cd3c40dfac84.png)

Also, I cant scroll while selecting months.

**Comment by LeagueRaINi** [comment]
> Im not sure if this is a bug or feature but you can activate keys from future :)

not a bug on my end at least, they only check if the purchase date is in between 2004 and 2099 
![raw](https://user-images.githubusercontent.com/19365835/201483994-21f10e1c-3825-466c-b941-ebbb2ab2f18c.png)

> Also, I cant scroll while selecting months.

outside the gui it works fine for me with the datetime selector open, inside the datetime selector u cannot do anything with the scroll wheel correct.

i also dont plan to implement it as there are enough ways to select a month/year

**Comment by tngflx** [comment]
you're a fking genius bro... I hope i can decipher what you wrote here. I just know how to cargo run it... wow
